"""Create deterministic firmware provenance and its frozen Python companion.

Copyright (c) 2026 Charlie Refvem
SPDX-License-Identifier: GPL-3.0-only
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


SHA_PATTERN = re.compile(r"[0-9a-fA-F]{40}")


def file_sha256(path: Path) -> str:
    """Return the full SHA-256 digest of a file."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git_sha(value: str) -> str:
    """Validate and normalize a full Git SHA supplied by the build."""
    if SHA_PATTERN.fullmatch(value) is None:
        raise argparse.ArgumentTypeError("expected a full 40-character Git SHA")
    return value.lower()


def boolean(value: str) -> bool:
    """Parse an explicit true/false command-line value."""
    normalized = value.lower()
    if normalized == "true":
        return True
    if normalized == "false":
        return False
    raise argparse.ArgumentTypeError("expected 'true' or 'false'")


def write_build_info(path: Path, values: dict[str, object]) -> None:
    """Write provenance constants consumed by the frozen me4305 module."""
    lines = [
        "# Generated by tools/build_manifest.py; do not edit.",
        "# SPDX-License-Identifier: GPL-3.0-only",
        "",
    ]
    for name in (
        "CUSTOM_REPOSITORY_SHA",
        "MICROPYTHON_SHA",
        "ULAB_SHA",
        "FROZEN_MODULES",
    ):
        lines.append(f"{name} = {values[name]!r}")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    repository_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--custom-repository-sha", required=True, type=git_sha)
    parser.add_argument("--micropython-sha", required=True, type=git_sha)
    parser.add_argument("--ulab-sha", required=True, type=git_sha)
    parser.add_argument("--micropython-ref", required=True)
    parser.add_argument("--ulab-ref", required=True)
    parser.add_argument("--frozen-opt-level", required=True, type=int,
                        choices=range(4))
    parser.add_argument("--generate-register-interface", required=True,
                        type=boolean)
    parser.add_argument("--repository-root", type=Path,
                        default=repository_root)
    parser.add_argument("--output", type=Path,
                        default=repository_root / "tools" /
                        "build_manifest.json")
    parser.add_argument("--build-info-output", type=Path,
                        default=repository_root / "ports" / "stm32" /
                        "boards" / "NUCLEO_L476RG" / "modules" /
                        "_build_info.py")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = args.repository_root.resolve()
    tools_dir = root / "tools"
    modules_dir = (root / "ports" / "stm32" / "boards" /
                   "NUCLEO_L476RG" / "modules")
    definitions = tools_dir / "register_definitions.json"
    generator = tools_dir / "register_map_generator.py"
    api_contract = tools_dir / "README.md"
    generated_module = tools_dir / "registerinterface.py"
    frozen_generated_module = modules_dir / "registerinterface.py"

    metadata_files = sorted(tools_dir.glob("register_metadata_*.json"))
    if args.generate_register_interface:
        if not generated_module.is_file():
            raise FileNotFoundError(generated_module)
        if not frozen_generated_module.is_file():
            raise FileNotFoundError(frozen_generated_module)
        if len(metadata_files) != 1:
            raise RuntimeError(
                "expected exactly one register_metadata_*.json file, found "
                f"{len(metadata_files)}"
            )
    else:
        metadata_files = []

    frozen_modules = sorted(
        {path.stem for path in modules_dir.glob("*.py")} | {"_build_info"}
    )
    build_values = {
        "CUSTOM_REPOSITORY_SHA": args.custom_repository_sha,
        "MICROPYTHON_SHA": args.micropython_sha,
        "ULAB_SHA": args.ulab_sha,
        "FROZEN_MODULES": tuple(frozen_modules),
    }
    write_build_info(args.build_info_output, build_values)

    register_outputs = {
        "generated_module": None,
        "api_manifest": None,
    }
    if args.generate_register_interface:
        metadata = metadata_files[0]
        module_hash = file_sha256(generated_module)
        if file_sha256(frozen_generated_module) != module_hash:
            raise RuntimeError(
                "frozen registerinterface.py does not match generator output"
            )
        api_data = json.loads(metadata.read_text(encoding="utf-8"))
        if api_data.get("generated_module_sha256") != module_hash:
            raise RuntimeError(
                "register API manifest does not match registerinterface.py"
            )
        if api_data.get("schema_sha256") != file_sha256(definitions):
            raise RuntimeError(
                "register API manifest does not match register_definitions.json"
            )
        register_outputs = {
            "generated_module": {
                "path": "tools/registerinterface.py",
                "sha256": module_hash,
            },
            "api_manifest": {
                "filename": metadata.name,
                "sha256": file_sha256(metadata),
            },
        }

    manifest = {
        "manifest_version": 1,
        "firmware": {
            "name": "ME 4305 Firmware",
            "board": "NUCLEO_L476RG",
            "custom_repository_sha": args.custom_repository_sha,
            "micropython_sha": args.micropython_sha,
            "ulab_sha": args.ulab_sha,
        },
        "register_interface": {
            "enabled": args.generate_register_interface,
            "inputs": {
                "definitions": {
                    "path": "tools/register_definitions.json",
                    "sha256": file_sha256(definitions),
                },
                "generator": {
                    "path": "tools/register_map_generator.py",
                    "sha256": file_sha256(generator),
                },
                "api_contract": {
                    "path": "tools/README.md",
                    "sha256": file_sha256(api_contract),
                },
            },
            "outputs": register_outputs,
            "options": {
                "use_literals": True,
                "use_substructs": False,
                "private_dicts": True,
            },
        },
        "frozen_custom_modules": frozen_modules,
        "build_options": {
            "micropython_ref": args.micropython_ref,
            "ulab_ref": args.ulab_ref,
            "micropy_frozen_opt_level": args.frozen_opt_level,
            "generate_register_interface": args.generate_register_interface,
            "user_c_module": "ulab",
        },
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as outfile:
        json.dump(manifest, outfile, indent=2, sort_keys=True)
        outfile.write("\n")


if __name__ == "__main__":
    main()
